# Generated by Django 2.1.3 on 2019-03-21 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asmt_no', models.PositiveSmallIntegerField()),
                ('announcement_date', models.DateField()),
                ('due_datetime', models.DateTimeField()),
                ('asmt_group', models.PositiveSmallIntegerField()),
                ('asmt_file', models.FileField(upload_to='asmt/')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveSmallIntegerField()),
                ('asmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('MCS', 'Masters in Computer Science'), ('MCA', 'Masters in Comuter Applications')], max_length=3)),
                ('rollno', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('Sem-I', 'Semester One'), ('Sem-II', 'Semester Two'), ('Sem-III', 'Semester Three'), ('Sem-IV', 'Semester Four'), ('Sem-V', 'Semester Five'), ('Sem-VI', 'Semester Six')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subj_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('sub_sem', models.CharField(choices=[('Sem-I', 'Semester One'), ('Sem-II', 'Semester Two'), ('Sem-III', 'Semester Three'), ('Sem-IV', 'Semester Four'), ('Sem-V', 'Semester Five'), ('Sem-VI', 'Semester Six')], max_length=10)),
                ('course', models.CharField(choices=[('MCS', 'Masters in Computer Science'), ('MCA', 'Masters in Comuter Applications')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_datetime', models.DateTimeField()),
                ('asmt_solution_file', models.FileField(upload_to='asmt_submission/')),
                ('asmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('cid', 'teacher_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('subject', 'asmt_no')},
        ),
    ]
