# Generated by Django 2.1.3 on 2019-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190323_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='asmt_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
