# Generated by Django 2.1.3 on 2019-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190322_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('instructor', 'INSTRUCTOR')], default='students', max_length=30),
        ),
    ]
